export const projects = [
  {
    title: 'Social Network',
    description: "Social network app is the project codded with jQuery, html and css. Cookies and sessions are implemented using JS. Log in, sign up, post, like and comment functions are also implemented using JS and JQuery too and mockAPI as a database.",
      image: '/images/1.png',
      tags: ['jQuery', 'HTML', 'CSS', 'mockAPI'],
    source: 'https://github.com/vidacicvuk/Social-Network-App-HTML-CSS-JS-JQUERY-mockAPI',
    visit: '',
    video_demo: 'https://github.com/vidacicvuk/Social-Network-App-HTML-CSS-JS-JQUERY-mockAPI#readme',
    id: 0,
    video: '/images/1.mp4',
  },
  {
    title: 'Simon Game',
    description:"Simon Game, the application written with the HTML, CSS and jQuery. The Simon game is the exciting electronic game of lights and sounds in which players must repeat random sequences of lights by pressing the colored pads in the correct order. It's fast-paced play, with lights and sounds that can challenge you.",
    image: '/images/2.png',
    tags: ['HTML','CSS', 'JavaScript'],
    source: 'https://github.com/vidacicvuk/Simon-Game-HTML-CSS-jQuery',
    visit: 'https://vidacicvuk.github.io/Simon-Game-HTML-CSS-jQuery/',
    video_demo: 'https://github.com/vidacicvuk/Simon-Game-HTML-CSS-jQuery#readme',
    id: 1,
    video: '/images/2.mp4',
  },
  {
    title: 'ToDo List',
    description: "ToDoList project is my introduction to mongoDB. It is application which will remember your ToDo things, you can add a new thing ToDo and when you check it, it will be removed from the list.",
      image: '/images/3.jpg',
      tags: ['JavaScript', 'mongoDB'],
    source: 'https://github.com/vidacicvuk/To-Do-List-Project',
    visit: '',
    video_demo: 'https://github.com/vidacicvuk/To-Do-List-Project#readme',
    id: 2,
    video: '/images/3.mp4',
  },
  {
    title: 'Blog Website',
    description: "The Blog Website is written with EJS, JS, HTML, and CSS, and the database is implemented using MongoDB.You can read all posts, if you have an authentication username and password you can add a new post and remove it.",
    image: '/images/4.jpg',
    tags: ['EJS', 'mongoDB'],
    source: 'https://github.com/vidacicvuk/Blog-Website-EJS',
    visit: '',
    video_demo: 'https://github.com/vidacicvuk/Blog-Website-EJS#readme',
    id: 3,
    video: '/images/4.mp4',
  },
  {
    title: 'Wiki-API-RESTful-API',
    description: "This application is small demonstration of knowledge of RESTfull APIs. Wiki-API is the server which will handle all your RESTfull API requests. Small database of 'articles' is implemented using mongoDB. With the RESTfull APIs you can add, modify, get and delete articles.",
    image: '/images/5.jpg',
    tags: ['JavaScript', 'RESTful API','mongoDB'],
    source: 'https://github.com/vidacicvuk/Wiki-API-RESTful-API',
    visit: '',
    video_demo: 'https://github.com/vidacicvuk/Wiki-API-RESTful-API#readme',
    id: 4,
    video: '/images/5.mp4',
  },
  {
    title: 'Secrets App',
    description: "'Secrets' is the social network where you can share anonymously your secret with other people and where you can read secrets from other people too. This project is developed with node.js, HTML and CSS. Accent in this project is on cookies which are implemented on the back-end side using 'passport', passwords of the users are hashed and log in/register with Google/Facebook is implemented too.",
    image: '/images/6.jpg',
    tags: ['EJS', 'JavaScript','mongoDB'],
    source: 'https://github.com/vidacicvuk/Secrets-Aplication',
    visit: '',
    video_demo: 'https://github.com/vidacicvuk/Secrets-Aplication#readme',
    id: 5,
    video: '/images/6.mp4',
  },
  {
    title: 'KeeperApp Motoko',
    description: "Keeper App is an application with the React frontend and the ICT as a backend. Backend is written using Motoko and this is my first web3 app. The application represents a blank board on which you can put your notes and remove them when you don't need them anymore.",
    image: '/images/7.jpg',
    tags: ['React', 'Motoko','Web3'],
    source: 'https://github.com/vidacicvuk/KeeperApp-React-Motoko',
    visit: '',
    video_demo: 'https://github.com/vidacicvuk/KeeperApp-React-Motoko#readme',
    id: 6,
    video: '/images/7.mp4',
  }
];

export const TimeLineData = [
  { year: 2019, text: 'Started my journey', },
  { year: 2019, text: 'Bachelor with Honours in Electrical and Computer Engineering (B.Elec.Comp.Eng.)', },
  { year: 2019, text: 'Started to work in the automotive industry as a software engineer.', },
  { year: 2021, text: 'Master in Electrical and Computer Engineering (M.El.Comp.Eng.)', },
  { year: 2022, text: 'Started my freelance web2/web3 development journey.', },
];